import { sidebar } from "vuepress-theme-hope";

export const zhSidebarConfig = sidebar({
  "/dotnetcore/examples/": [
    {
      text: ".NET Core示例",
      collapsible: true,
      children: [
        "README.md",
        "freesql-in-aspnetcore-webapi-how-to-use",
        "freesql-sample-blog-restful-use-automapper",
        "identityserver4",
        "qiniu-object-storages",
        "imcore-chat",
        "nacos-aspnetcore",
        "serilog-tutorial",
        "NET6Startup",
        "ASPNETCore6-Add-Startup-Clean",
        "ASPNETCore-Supervisord-Ubuntu",
        "ASPNETCore-Systemd-Ubuntu",
      ],
    },
  ],
  "/dotnetcore/lin-cms/": [
    {
      text: "入门指南",
      collapsible: true,
      children: [
        "README.md",
        "backend-quickstart.md",
        "frontend-quickstart.md",
        "deployment.md",
        "faq.md",
      ],
    },
    {
      text: "核心概念",
      collapsible: true,
      children: [
        "technology-stack.md",
        "project-structure.md",
        "database-design.md",
        "authorize.md",
        "logger.md",
        "file-upload.md",
      ],
    },
    {
      text: "开发进阶",
      collapsible: true,
      children: [
        "development-guide.md",
        "api-reference.md",
        "lincms-scaffolding.md",
        "autofac.md",
        "aspnetcore-repository-unitofwork.md",
        "newtonsoft-json-question.md",
        "dependency-injection-scrutor.md",
        "dynamic-authorization-in-aspnetcore.md",
        "Reflex-Assembly.md",
        "identityserver4-jwt.md",
        "stopwords.md",
        "spa-github-login.md",
        "qq-login.md",
        "rabbitmq.md",
        "scriban-README.md",
      ],
    },
    {
      text: "其他",
      collapsible: true,
      children: [
        "contributing.md",
        "github-actions.md",
        "change-sqlserver.md",
        "open-source-road.md",
        "pm-design-modules.md",
        "production-design.md",
      ],
    },
  ],
  "/dotnetcore/": [
    {
      text: "FreeKit",
      collapsible: true,
      link: "freekit/README.md",
      children: [
        "freekit/README.md",
        "freekit/Core.md",
        "freekit/Extras.md",
        "freekit/AspNetCore.Identity.FreeSql.md",
        "freekit/Email.md",
        "freekit/Modularity.md",
        "freekit/Localization.FreeSql.md",
      ],
    },
    {
      text: "Docker",
      collapsible: true,
      link: "docker/README.md",
      children: [
        "docker/README.md",
        "docker/Docker-Command.md",
        "docker/DockerHub.md",
        "docker/Docker-Baget.md",
        "docker/Docker-Jenkins.md",
        "docker/Docker-Elasticsearch.md",
        "docker/Docker-MySql.md",
        "docker/Docker-Nacos.md",
        "docker/Docker-Portainer.md",
        "docker/Docker-Redis.md",
        "docker/Docker-Nginx.md",
        "docker/Docker-RabbitMQ.md",
        "docker/Docker-CMS.md",
        "docker/Docker-ASPNETCore.md",
      ],
    },
  ],
  "/about/": [
    {
      text: "关于",
      prefix: "/about/",
      link: "/about/",
      collapsible: true,
    },
  ],
  "/navigation/": [
    {
      text: "导航",
      prefix: "/navigation/",
      link: "/navigation/",
      collapsible: true,
      children: [],
    },
  ],
  "/blogs/": [
    {
      text: "技术分享",
      collapsible: true,
      children: [
        "README.md",
        "git-emoji",
        "fluent-emoji-ms",
        "net-sqlite-encryption",
        "net-encoded-1",
        "delegate",
        "idlebus-freesql",
      ],
    },
  ]
});
