name: Sync to Git Mirror 
on:
    push:
        branches:
            - main
            - gh-pages

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Sync to Git Mirror 💕
              uses: wearerequired/git-mirror-action@master
              env:
                  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
              with:
                  source-repo: "git@github.com:luoyunchong/igeekfan-docs.git"
                  destination-repo: "git@gitee.com:igeekfan/igeekfan-docs.git"
